const TOGGLE_OPEN = "TOGGLE_OPEN";
const ADD_TO_CART_ITEMS = "ADD_TO_CART_ITEMS";
const REMOVE_FROM_CART_ITEMS = "REMOVE_FROM_CART_ITEMS";
const DELETE_ITEM = "DELETE_ITEM";

export { TOGGLE_OPEN, ADD_TO_CART_ITEMS, REMOVE_FROM_CART_ITEMS, DELETE_ITEM };
